// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tamagotchi.Models;

#nullable disable

namespace Tamagotchi.Migrations
{
    [DbContext(typeof(TamagotchiContext))]
    [Migration("20230525185913_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tamagotchi.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AmtFood")
                        .HasColumnType("int");

                    b.Property<int>("Attention")
                        .HasColumnType("int");

                    b.Property<int>("AttnMax")
                        .HasColumnType("int");

                    b.Property<int>("AttnMin")
                        .HasColumnType("int");

                    b.Property<int>("AttnPlus")
                        .HasColumnType("int");

                    b.Property<int>("FoodMax")
                        .HasColumnType("int");

                    b.Property<int>("FoodMin")
                        .HasColumnType("int");

                    b.Property<int>("FoodPlus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Rest")
                        .HasColumnType("int");

                    b.Property<int>("RestMax")
                        .HasColumnType("int");

                    b.Property<int>("RestMin")
                        .HasColumnType("int");

                    b.Property<int>("RestPlus")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("PetId");

                    b.ToTable("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
